const lyrics = [
    { time: 0, text: "Are you ready, hey, are you ready for this?", singer: "freddie" },
    { time: 2.5, text: "Are you hanging on the edge of your seat?", singer: "freddie" },
    { time: 4, text: "I need a break beat, uh", singer: "wyclef" },
    { time: 5.9, text: "Are you ready, hey, are you ready for this?", singer: "freddie" },
    { time: 12, text: "Are you hanging on the edge of your seat?", singer: "freddie" },
    { time: 12.5, text: "I need a break beat, uh", singer: "wyclef" },
    { time: 14, text: "Outta the doorway the bullets rip", singer: "freddie" },
    { time: 16, text: "Repeating to the sound of the beat, hey", singer: "freddie" },
    { time: 18, text: "Yo, a for the kids in the club that's ready to get bugged", singer: "wyclef" },
    { time: 21, text: "Another one bites the dust", singer: "freddie" },
    { time: 22.9, text: "And for the thugs with the burners that wanna blast off", singer: "wyclef" },
    { time: 25, text: "Another one bites the dust", singer: "freddie" },
    { time: 27, text: "And for the kids on the blocks, shootin' at the crooked cops—blaow!", singer: "wyclef" },
    { time: 30, text: "Another one bites the dust", singer: "freddie" },
    { time: 32, text: "And another one gone", singer: "wyclef" },
    { time: 33, text: "And another one gone", singer: "freddie" },
    { time: 34, text: "Another one bites the dust", singer: "freddie" },
    { time: 37, text: "Steve walks wearily down the street", singer: "freddie" },
    { time: 39, text: "With the brim pulled way down low", singer: "freddie" },
    { time: 41, text: "Some cat up in Brooklyn just got robbed with a Kangol", singer: "wyclef" },
    { time: 45, text: "Are you ready, hey, are you ready for this?", singer: "freddie" },
    { time: 48, text: "Are you hanging on the edge of your seat?", singer: "freddie" },
    { time: 50, text: "Out of the doorway, the bullets rip", singer: "freddie" },
    { time: 52, text: "Repeating to the sound of the beat, hey", singer: "freddie" },
    { time: 54.8, text: "My man got shot, and the block got hot", singer: "wyclef" },
    { time: 57.8, text: "Another one bites the dust", singer: "freddie" },
    { time: 59, text: "Yo, hey I hear more shots, this is like Fort Knox, kid", singer: "wyclef" },
    { time: 60.2, text: "Another one bites the dust", singer: "freddie" },
    { time: 64, text: "Yo, hold your breath", singer: "wyclef" },
    { time: 65, text: "And another one gone", singer: "freddie" },
    { time: 66, text: "Hold your breath", singer: "wyclef" },
    { time: 66.5, text: "And another one gone", singer: "freddie" },
    { time: 67, text: "Hold your breath", singer: "wyclef" },
    { time: 67.5, text: "Another one bites the dust", singer: "freddie" },
    { time: 68, text: "Yo, check it", singer: "wyclef" },
    { time: 68.5, text: "If you're a soldier at ease", singer: "wyclef" },
    { time: 69, text: "My military style is known to murder Nazis", singer: "wyclef" },
    { time: 71, text: "Brooklyn to Germany (Oh yeah) come on", singer: "wyclef" },
    { time: 73, text: "My kamikaze will blow the U2", singer: "wyclef" },
    { time: 75, text: "They hire Idi Amin in Timbuktu", singer: "wyclef" },
    { time: 77, text: "Whether you Hindu, or do the Voodoo", singer: "wyclef" },
    { time: 78, text: "You can't foresee this unless I bring the previews, yeah, yeah", singer: "wyclef" },
    { time: 80, text: "Yo, it's the number one rappin' band (Come on)", singer: "wyclef" },
    { time: 84, text: "Yo, this review will be critically acclaimed", singer: "wyclef" },
    { time: 89, text: "Leave you in critical pain, clinically insane", singer: "wyclef" },
    { time: 91, text: "The name Wyclef Jean, with a yes, yes y'all", singer: "wyclef" },
    { time: 93, text: "Better have a vest y'all, I'll blast, and bless y'all (Oh yeah)", singer: "wyclef" },
    { time: 96, text: "F-y'all, the mark of the beast, the triple six", singer: "wyclef" },
    { time: 98, text: "Time running out, listen to the tick (Oh yeah)", singer: "wyclef" },
    { time: 100, text: "If you see what I saw, then you seen what I seen", singer: "wyclef" },
    { time: 103, text: "If you know what I know, you know what I mean (Oh yeah)", singer: "wyclef" },
    
    { time: 105, text: "Commanding officer of the Navy SEAL team", singer: "wyclef" },
    { time: 107, text: "Once I give the orders, you feel the infrared beam (Oh yeah) Blaow!", singer: "wyclef" },
    { time: 108, text: "For all you critics, sayin' 'another remake'", singer: "wyclef" },
    { time: 112, text: "Another one bites the dust", singer: "freddie" },
    { time: 114, text: "Yo, if you know the deal, this is the master reel, kid", singer: "wyclef" },
    { time: 116, text: "Another one bites the dust (Oh yeah)", singer: "freddie" },
    { time: 118, text: "And another one gone", singer: "freddie" },
    { time: 119, text: "Right", singer: "wyclef" },
    { time: 120, text: "And another one gone", singer: "freddie" },
    { time: 121, text: "Right", singer: "wyclef" },
    { time: 122, text: "Another one bites the dust, hey", singer: "freddie" },
    { time: 123, text: "Freddie Mercury, where you at yo?", singer: "wyclef" },
    { time: 123.4, text: "How do you think I'm gonna get along", singer: "freddie" },
    { time: 125, text: "Without you when you're gone (Oh yeah)", singer: "freddie" },
    { time: 127, text: "I need a break yo", singer: "wyclef" },
    { time: 129, text: "If you're ready for the first of the month", singer: "wyclef" },
    { time: 131, text: "For that welfare check, come on", singer: "wyclef" },
    { time: 133, text: "Kicked me out on my own", singer: "freddie" },
    { time: 134, text: "I need a break beat", singer: "wyclef" },
    { time: 139, text: "Are you happy, are you satisfied?", singer: "freddie" },
    { time: 140, text: "How long can you stand the heat?", singer: "freddie" },
    { time: 142, text: "I need a break beat", singer: "wyclef" },
    { time: 143, text: "Outta the doorway, the bullets rip", singer: "freddie" },
    { time: 13.4, text: "To the sound of the beat, look out", singer: "freddie" },
    { time: 144, text: "Yo, bulletproof vests, like the wild, wild west", singer: "wyclef" },
    { time: 145, text: "Another one bites the dust", singer: "freddie" },
    { time: 146, text: "Yo, this is a stickup, now take off your Rolex", singer: "wyclef" },
    { time: 147, text: "Another one bites the dust", singer: "freddie" },
    { time: 148, text: "Yo, dirty money, good money, yo it's all money-money", singer: "wyclef" },
    { time: 149, text: "Another one bites the dust", singer: "freddie" },
    { time: 150, text: "Yo, Dirty Cash", singer: "wyclef" },
    { time: 151, text: "And another one gone", singer: "freddie" },
    { time: 152, text: "Dirty Cash", singer: "wyclef" },
    { time: 153, text: "And another one gone", singer: "freddie" },
    { time: 154, text: "The adventures of Dirty Cash", singer: "wyclef" },
    { time: 155, text: "Another one bites the dust", singer: "freddie" },
   
    { time: 159, text: "Yo, for the love for the cash, I'll blast you in my path", singer: "wyclef" }, 
    { time: 161, text: "Keep my eyes on the math, you cats don't know the half (Oh yeah)", singer: "wyclef" },
    { time: 163, text: "As far as I'm concerned, you cats can burn in flames", singer: "wyclef" },
    { time: 165, text: "This ain't no game, I'mma start callin' names (Oh yeah)", singer: "wyclef" },
    { time: 167, text: "So come get me, if you know the one-fifty", singer: "wyclef" },
    { time: 168, text: "A million refugees ready to bust with me (Oh yeah)", singer: "wyclef" },
    { time: 170, text: "Bloody, filthy, in this rap shhh—", singer: "wyclef" },
    { time: 171, text: "You gonna have to kill me, since you can't beat me (Oh yeah)", singer: "wyclef" },
    { time: 173, text: "Pras, Dirty, Cash, you're the greedy", singer: "wyclef" },
    { time: 175, text: "Believe me, you gotta let me fly like R. Kelly (Oh yeah)", singer: "wyclef" },
    { time: 177, text: "Bite another dust with my man Freddie Mercury", singer: "wyclef" },
    { time: 178, text: "What height nineties got ya cash, wannabe crazy (Oh yeah)", singer: "wyclef" },
 
 
    { time: 185, text: "Practically, I tactically destroy", singer: "wyclef" }, 
    { time: 188, text: "Deploy more decoys than a presidential convoy (Oh yeah)", singer: "wyclef" },
    { time: 191, text: "My whole envoy stay camouflaged out", singer: "wyclef" },
    { time: 193, text: "And when I walk the street, I take the refugee route (Oh yeah)", singer: "wyclef" },
    { time: 195, text: "This one go out to all my thugs in the borough", singer: "wyclef" },
    { time: 197, text: "Soldiers stay thorough, like Kilamanjaro (Oh yeah)", singer: "wyclef" },
    { time: 199, text: "Split it with an arrow, my girl platoon roll", singer: "wyclef" },
    { time: 201, text: "Outta control, the female Mandingos (Oh yeah)", singer: "wyclef" },
    { time: 203, text: "Free, I evolve from the egg of a seminarian", singer: "wyclef" },
    { time: 202, text: "Don't go down, 'cause I'm a vegetarian (Oh yeah)", singer: "wyclef" },
    { time: 205, text: "And when I bust, it ain't 'in God we trust'", singer: "wyclef" },
    { time: 207, text: "And if you bring a gun, you better bring a black tusk (Oh yeah)", singer: "wyclef" },
    // Outro
    { time: 213, text: "She looked into my eyes and said FBI", singer: "wyclef" },
    { time: 215, text: "Another one bites the dust (Oh yeah)", singer: "freddie" },
    { time: 216, text: "She said she loved me, she was a spy who lied", singer: "wyclef" },
    { time: 217, text: "Another one bites the dust", singer: "freddie" },
    { time: 218, text: "Right", singer: "wyclef" },
    { time: 219, text: "I could relate, could you relate?", singer: "wyclef" },
    { time: 221, text: "Another one bites the dust", singer: "freddie" },
    { time: 223, text: "Jerry 'Wonda', The Product (Oh-oh)", singer: "wyclef" },
    { time: 225, text: "Another one bites the dust", singer: "freddie" },
    { time: 226, text: "Yo, Canibus, John Forté", singer: "wyclef" },
    { time: 229, text: "Don't you know we coming for you?", singer: "wyclef" },
    { time: 231, text: "Another one bites the dust", singer: "freddie" },
    { time: 232, text: "Yo, Dirty Cash, and baby Free", singer: "wyclef" },
    { time: 234, text: "Another one bites the dust", singer: "freddie" },
    { time: 236, text: "And another one gone", singer: "freddie" },
    { time: 238, text: "Wyclef Jean", singer: "wyclef" },
    { time: 239, text: "And another one gone", singer: "freddie" },
    { time: 240, text: "Freddie Mercury, ha-ha", singer: "wyclef" },
    { time: 242, text: "Another one bites the dust, yeah", singer: "freddie" },
    { time: 241, text: "I'm out baby", singer: "wyclef" },
    { time: 242, text: "Navy SEALs!", singer: "wyclef" },
    { time: 245, text: "Another one bites the dust", singer: "freddie" },
    { time: 248, text: "Another one bites the dust", singer: "freddie" },
    { time: 249, text: "Another one bites the dust", singer: "freddie" }
  ];
  
  let currentLyricIndex = 0;
  const audio = document.getElementById("audio");
  const freddieLyricElement = document.getElementById("lyric-freddie");
  const wyclefLyricElement = document.getElementById("lyric-others");
  
  audio.addEventListener("play", () => {
    setInterval(displayLyrics, 100);
  });
  
  function displayLyrics() {
    const currentTime = audio.currentTime;
    if (currentLyricIndex < lyrics.length && currentTime >= lyrics[currentLyricIndex].time) {
      if (lyrics[currentLyricIndex].singer === "freddie") {
        freddieLyricElement.textContent = lyrics[currentLyricIndex].text;
      } else {
        wyclefLyricElement.textContent = lyrics[currentLyricIndex].text;
      }
      currentLyricIndex++;
    }
  }